import type { Metadata } from "next";
import { Nunito, Raleway } from "next/font/google";
import "@styles/global.scss";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import NavModalProvider from "@/app/components/NavModalProvider";
config.autoAddCss = false

const raleway = Raleway({
  subsets: ["latin"],
  variable: '--ff-primary'
});
const nunito = Nunito({
  subsets: ["latin"],
  variable: '--ff-secondary'
});

export const metadata: Metadata = {
  title: "CozyCat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.variable} ${nunito.variable}`}>
      <body>
          <NavModalProvider>
            {children}
          </NavModalProvider>
      </body>
    </html>
  );
}
